server:
  port: 8081
  servlet:
    context-path: /api/mail

spring:
  application:
    name: mail-service
  # MAIL
  mail:
    host: smtp.gmail.com
    port: 587
    username: ntduc.291099@gmail.com
    password: vshvspgrajftlurt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# EUREKA (register service)
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
 


