server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: mail_v2
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/v2/**
        - id: batch_v2
          uri: lb://batch-service
          predicates:
            - Path=/api/batch/v2/**
        - id: schoolservice_v2
          uri: lb://SCHOOL-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/v2/**

        - id: education-service
          uri: lb://education-service
          predicates:
            - Path=/api/education/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**
        - id: utils-service
          uri: lb://utils-service
          predicates:
            - Path=/api/utils/**         


management:
  endpoint:
    gateway:
      access: true


